### PR TITLE
Add execute plan for other DBMS

### PR DESCRIPTION
**Pull request by tkopets**
Added explain query for:

  * PostgreSQL
  * MySQL
  * Vertica
  * SQLite

As well as added default keyboard shortcut [ctrl+e, ctrl+x] for explain plan command.

### CODE REVIEW

**Comment by tkopets** [comment]
I've done some testing today, and there are a few more issues with EXPLAIN on those other DBMS.

1. It does not work with multiline statements with other DBMS, since additional semicolon is striped.
e.g. highlighting the piece of text below:
```
select * from tbl1;
select * from tbl2;
```
Produces result below and returns errors, since the trailing semicolons are missing.
```
explain select * from tbl1
explain select * from tbl2
```

2. It does not work on single statements when additional whitespace is selected as well and tries to do an explain on empty lines.
e.g. highlighting the piece of text below:
```
select * from tbl;


```

would produce:
```
explain select * from tbl;
explain 
```

Note the last one produces explain on empty query.

**Comment by tkopets** [comment]
Fixed both problems described above.

**Comment by tkopets** [comment]
Added `KeyError` exception handling, so if DMBS does not have support (options) for explain plan command it would be silently ignored.

**Comment by ngr-t** [comment]
Great! I couldn't find time to set up environments to test other DBMS until now, thank you so much!

**Comment by ngr-t** [comment]
Looks good to me. Do you plan to edit this anymore?

**Comment by tkopets** [comment]
Thanks!
No more edits for now.
I'll update the documentation, but that will happen on a separate branch.

**Pull request merged**
